services:
  frontend:
    profiles:
      - production
    build:
      context: .
      target: production
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=${VITE_API_URL:-https://corion.mx/cws/eorder_b/Backend/public/index.php/api}
      - VITE_REVERB_HOST=${VITE_REVERB_HOST:-corion.mx}
      - VITE_REVERB_PORT=${VITE_REVERB_PORT:-443}
      - VITE_REVERB_SCHEME=${VITE_REVERB_SCHEME:-https}
      - VITE_REVERB_APP_KEY=${VITE_REVERB_APP_KEY:-ds9d0dge2etayrnrzaca}
      - VITE_BASE_PATH=${VITE_BASE_PATH:-/cws/eorder_b/}
    restart: unless-stopped

  frontend-dev:
    profiles:
      - development
    build:
      context: .
      target: development
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8000/api}
      - VITE_REVERB_HOST=${VITE_REVERB_HOST:-localhost}
      - VITE_REVERB_PORT=${VITE_REVERB_PORT:-8080}
      - VITE_REVERB_SCHEME=${VITE_REVERB_SCHEME:-http}
      - VITE_REVERB_APP_KEY=${VITE_REVERB_APP_KEY:-ds9d0dge2etayrnrzaca}
      - VITE_BASE_PATH=${VITE_BASE_PATH:-/}
    restart: unless-stopped
